api_platform:
    title: 'Aides Travaux API'
    version: '1.0.0'
    show_webby: false
    mapping:
        paths:
            - '%kernel.project_dir%/config/api/resources'
            - '%kernel.project_dir%/src/Api/Resource'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    http_cache:
        public: true
    defaults:
        cache_headers:
            max_age: 3600
            shared_max_age: 3600
            vary: ['Content-Type', 'Authorization', 'Origin']
