api_platform:
    title: 'Aides Travaux API'
    version: '1.0.0'
    show_webby: false
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/src/Model'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
