security:
    enable_authenticator_manager: true
    password_hashers:
        App\Entity\Utilisateur:
            algorithm: auto
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/login
            stateless: true
            json_login:
                check_path: /login_check
                username_path: email
                password_path: plainPassword
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern: ^
            stateless: true
            jwt: ~

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
