vich_uploader:
    db_driver: orm
    twig: false

    mappings:
        dispositifs:
            uri_prefix: '%app.path.dispositifs%'
            upload_destination: '%kernel.project_dir%/public%app.path.dispositifs%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
