vich_uploader:
    db_driver: orm

    mappings:
        logo:
            uri_prefix: /logo
            upload_destination: '%kernel.project_dir%/public/logo'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
