App\Entity\Secteur:
    attributes:
        normalization_context:
            groups: ['secteur:read']
        denormalization_context:
            groups: ['secteur:write']
    collectionOperations:
        get:
            filters: ['secteur.search_filter', 'secteur.exists_filter']
        post:
            security: 'is_granted("ROLE_ADMIN")'
    itemOperations:
        get: ~
        put:
            security: 'is_granted("ROLE_ADMIN")'
        delete:
            security: 'is_granted("ROLE_ADMIN")'
